print("    ", end="*\n")
print("   * ", end="*\n")
print("  *   ", end="*\n")
print(" *     ", end="*\n")
print("***","***", sep="   ", end="\n")
print("  *   ", end="*\n")
print("  *   ", end="*\n")
print("  ****", end="*\n")